default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: raboy1997
  password: vfrc1997

development:
  <<: *default
  database: diplom_site_development

test:
  <<: *default
  database: diplom_site_test

production:
  <<: *default
  database: diplom_site_production
  username: raboy1997
  password: vfrc1997
